services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: second_brain
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d second_brain"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 